DATA_SEG SEGMENT
    NUM1 DW 5686H
    NUM2 DW 1234H
    SUM DW 0
DATA_SEG ENDS

CODE_SEG SEGMENT
    ASSUME CS:CODE_SEG, DS:DATA_SEG
    
START:
    MOV AX, DATA_SEG
    MOV DS, AX
    MOV AX, NUM1
    MOV BX, NUM2
    ADD AL, BL
    DAA
    MOV CL, AL
    ADC AH, BH
    MOV CH, AH
    MOV SUM, CX
    MOV AH, 4CH
    INT 21H
    
CODE_SEG ENDS
END START