DATA_SEG SEGMENT
    NUM DB 5
    FACT DB 0
DATA_SEG ENDS

CODE_SEG SEGMENT
    ASSUME CS:CODE_SEG, DS:DATA_SEG
START:
    MOV AX, DATA_SEG
    MOV DS, AX
    
    MOV AL, 1
    MOV CL, NUM
    
    AGAIN :MUL CL
           DEC CL
           JNZ AGAIN

    MOV FACT, AL    
    MOV AH, 4CH
    INT 21H
CODE_SEG ENDS
END START