DATA_SEG SEGMENT
    SOURCE_ARR DB 75H, 76H, 77H, 78H, 79H
    DEST_ARR DB 5 DUP(0)
DATA_SEG ENDS

CODE_SEG SEGMENT
    ASSUME CS:CODE_SEG, DS:DATA_SEG
    
START:
    MOV AX, DATA_SEG
    MOV DS, AX
    ;LEA SI, SOURCE_ARR
    ;LEA DI, DEST_ARR
    MOV SI, OFFSET SOURCE_ARR
    MOV DI, OFFSET DEST_ARR
    
    ;MOV BL, 5
    MOV CL, 5
    
AGAIN:
    MOV AL, [SI]
    MOV [DI], AL
    INC SI
    INC DI
    ;DEC BL
    DEC CL
    JNZ AGAIN
    
    MOV AH, 4CH
    INT 21H
    
CODE_SEG ENDS
END START