DATA_SEG SEGMENT
    PACKED_BCD DB 77H
    HIGH_DIGIT DB 0
    LOW_DIGIT DB 0
DATA_SEG ENDS

CODE_SEG SEGMENT 
    ASSUME CS:CODE_SEG, DS:DATA_SEG

START:
    MOV AX, DATA_SEG
    MOV DS, AX
    MOV AL, PACKED_BCD
    AND AL, 0F0H
    MOV CL, 4
    ROR AL, CL
    MOV HIGH_DIGIT, AL
    MOV AL, PACKED_BCD
    AND AL, 0FH
    MOV LOW_DIGIT, AL
    MOV AH,4CH
    INT 21H
    
CODE_SEG ENDS
    
END START
   
    
    